// Code generated by go-swagger; DO NOT EDIT.

package role

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/chenrui333/go-looker/models"
)

// CreatePermissionSetReader is a Reader for the CreatePermissionSet structure.
type CreatePermissionSetReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *CreatePermissionSetReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewCreatePermissionSetOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 400:
		result := NewCreatePermissionSetBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 404:
		result := NewCreatePermissionSetNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 409:
		result := NewCreatePermissionSetConflict()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 422:
		result := NewCreatePermissionSetUnprocessableEntity()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewCreatePermissionSetOK creates a CreatePermissionSetOK with default headers values
func NewCreatePermissionSetOK() *CreatePermissionSetOK {
	return &CreatePermissionSetOK{}
}

/*CreatePermissionSetOK handles this case with default header values.

Permission Set
*/
type CreatePermissionSetOK struct {
	Payload *models.PermissionSet
}

func (o *CreatePermissionSetOK) Error() string {
	return fmt.Sprintf("[POST /permission_sets][%d] createPermissionSetOK  %+v", 200, o.Payload)
}

func (o *CreatePermissionSetOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.PermissionSet)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewCreatePermissionSetBadRequest creates a CreatePermissionSetBadRequest with default headers values
func NewCreatePermissionSetBadRequest() *CreatePermissionSetBadRequest {
	return &CreatePermissionSetBadRequest{}
}

/*CreatePermissionSetBadRequest handles this case with default header values.

Bad Request
*/
type CreatePermissionSetBadRequest struct {
	Payload *models.Error
}

func (o *CreatePermissionSetBadRequest) Error() string {
	return fmt.Sprintf("[POST /permission_sets][%d] createPermissionSetBadRequest  %+v", 400, o.Payload)
}

func (o *CreatePermissionSetBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewCreatePermissionSetNotFound creates a CreatePermissionSetNotFound with default headers values
func NewCreatePermissionSetNotFound() *CreatePermissionSetNotFound {
	return &CreatePermissionSetNotFound{}
}

/*CreatePermissionSetNotFound handles this case with default header values.

Not Found
*/
type CreatePermissionSetNotFound struct {
	Payload *models.Error
}

func (o *CreatePermissionSetNotFound) Error() string {
	return fmt.Sprintf("[POST /permission_sets][%d] createPermissionSetNotFound  %+v", 404, o.Payload)
}

func (o *CreatePermissionSetNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewCreatePermissionSetConflict creates a CreatePermissionSetConflict with default headers values
func NewCreatePermissionSetConflict() *CreatePermissionSetConflict {
	return &CreatePermissionSetConflict{}
}

/*CreatePermissionSetConflict handles this case with default header values.

Resource Already Exists
*/
type CreatePermissionSetConflict struct {
	Payload *models.Error
}

func (o *CreatePermissionSetConflict) Error() string {
	return fmt.Sprintf("[POST /permission_sets][%d] createPermissionSetConflict  %+v", 409, o.Payload)
}

func (o *CreatePermissionSetConflict) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewCreatePermissionSetUnprocessableEntity creates a CreatePermissionSetUnprocessableEntity with default headers values
func NewCreatePermissionSetUnprocessableEntity() *CreatePermissionSetUnprocessableEntity {
	return &CreatePermissionSetUnprocessableEntity{}
}

/*CreatePermissionSetUnprocessableEntity handles this case with default header values.

Validation Error
*/
type CreatePermissionSetUnprocessableEntity struct {
	Payload *models.ValidationError
}

func (o *CreatePermissionSetUnprocessableEntity) Error() string {
	return fmt.Sprintf("[POST /permission_sets][%d] createPermissionSetUnprocessableEntity  %+v", 422, o.Payload)
}

func (o *CreatePermissionSetUnprocessableEntity) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ValidationError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
