// Code generated by go-swagger; DO NOT EDIT.

package role

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/chenrui333/go-looker/models"
)

// NewCreatePermissionSetParams creates a new CreatePermissionSetParams object
// with the default values initialized.
func NewCreatePermissionSetParams() *CreatePermissionSetParams {
	var ()
	return &CreatePermissionSetParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewCreatePermissionSetParamsWithTimeout creates a new CreatePermissionSetParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewCreatePermissionSetParamsWithTimeout(timeout time.Duration) *CreatePermissionSetParams {
	var ()
	return &CreatePermissionSetParams{

		timeout: timeout,
	}
}

// NewCreatePermissionSetParamsWithContext creates a new CreatePermissionSetParams object
// with the default values initialized, and the ability to set a context for a request
func NewCreatePermissionSetParamsWithContext(ctx context.Context) *CreatePermissionSetParams {
	var ()
	return &CreatePermissionSetParams{

		Context: ctx,
	}
}

// NewCreatePermissionSetParamsWithHTTPClient creates a new CreatePermissionSetParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewCreatePermissionSetParamsWithHTTPClient(client *http.Client) *CreatePermissionSetParams {
	var ()
	return &CreatePermissionSetParams{
		HTTPClient: client,
	}
}

/*CreatePermissionSetParams contains all the parameters to send to the API endpoint
for the create permission set operation typically these are written to a http.Request
*/
type CreatePermissionSetParams struct {

	/*Body
	  Permission Set

	*/
	Body *models.PermissionSet

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the create permission set params
func (o *CreatePermissionSetParams) WithTimeout(timeout time.Duration) *CreatePermissionSetParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the create permission set params
func (o *CreatePermissionSetParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the create permission set params
func (o *CreatePermissionSetParams) WithContext(ctx context.Context) *CreatePermissionSetParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the create permission set params
func (o *CreatePermissionSetParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the create permission set params
func (o *CreatePermissionSetParams) WithHTTPClient(client *http.Client) *CreatePermissionSetParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the create permission set params
func (o *CreatePermissionSetParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the create permission set params
func (o *CreatePermissionSetParams) WithBody(body *models.PermissionSet) *CreatePermissionSetParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the create permission set params
func (o *CreatePermissionSetParams) SetBody(body *models.PermissionSet) {
	o.Body = body
}

// WriteToRequest writes these params to a swagger request
func (o *CreatePermissionSetParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
