// Code generated by go-swagger; DO NOT EDIT.

package api_auth

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/swag"

	strfmt "github.com/go-openapi/strfmt"
)

// NewLoginUserParams creates a new LoginUserParams object
// with the default values initialized.
func NewLoginUserParams() *LoginUserParams {
	var ()
	return &LoginUserParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewLoginUserParamsWithTimeout creates a new LoginUserParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewLoginUserParamsWithTimeout(timeout time.Duration) *LoginUserParams {
	var ()
	return &LoginUserParams{

		timeout: timeout,
	}
}

// NewLoginUserParamsWithContext creates a new LoginUserParams object
// with the default values initialized, and the ability to set a context for a request
func NewLoginUserParamsWithContext(ctx context.Context) *LoginUserParams {
	var ()
	return &LoginUserParams{

		Context: ctx,
	}
}

// NewLoginUserParamsWithHTTPClient creates a new LoginUserParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewLoginUserParamsWithHTTPClient(client *http.Client) *LoginUserParams {
	var ()
	return &LoginUserParams{
		HTTPClient: client,
	}
}

/*LoginUserParams contains all the parameters to send to the API endpoint
for the login user operation typically these are written to a http.Request
*/
type LoginUserParams struct {

	/*UserID
	  Id of user.

	*/
	UserID int64

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the login user params
func (o *LoginUserParams) WithTimeout(timeout time.Duration) *LoginUserParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the login user params
func (o *LoginUserParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the login user params
func (o *LoginUserParams) WithContext(ctx context.Context) *LoginUserParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the login user params
func (o *LoginUserParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the login user params
func (o *LoginUserParams) WithHTTPClient(client *http.Client) *LoginUserParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the login user params
func (o *LoginUserParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithUserID adds the userID to the login user params
func (o *LoginUserParams) WithUserID(userID int64) *LoginUserParams {
	o.SetUserID(userID)
	return o
}

// SetUserID adds the userId to the login user params
func (o *LoginUserParams) SetUserID(userID int64) {
	o.UserID = userID
}

// WriteToRequest writes these params to a swagger request
func (o *LoginUserParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param user_id
	if err := r.SetPathParam("user_id", swag.FormatInt64(o.UserID)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
