// Code generated by go-swagger; DO NOT EDIT.

package config

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/chenrui333/go-looker/models"
)

// NewUpdateCustomWelcomeEmailTestParams creates a new UpdateCustomWelcomeEmailTestParams object
// with the default values initialized.
func NewUpdateCustomWelcomeEmailTestParams() *UpdateCustomWelcomeEmailTestParams {
	var ()
	return &UpdateCustomWelcomeEmailTestParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewUpdateCustomWelcomeEmailTestParamsWithTimeout creates a new UpdateCustomWelcomeEmailTestParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewUpdateCustomWelcomeEmailTestParamsWithTimeout(timeout time.Duration) *UpdateCustomWelcomeEmailTestParams {
	var ()
	return &UpdateCustomWelcomeEmailTestParams{

		timeout: timeout,
	}
}

// NewUpdateCustomWelcomeEmailTestParamsWithContext creates a new UpdateCustomWelcomeEmailTestParams object
// with the default values initialized, and the ability to set a context for a request
func NewUpdateCustomWelcomeEmailTestParamsWithContext(ctx context.Context) *UpdateCustomWelcomeEmailTestParams {
	var ()
	return &UpdateCustomWelcomeEmailTestParams{

		Context: ctx,
	}
}

// NewUpdateCustomWelcomeEmailTestParamsWithHTTPClient creates a new UpdateCustomWelcomeEmailTestParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewUpdateCustomWelcomeEmailTestParamsWithHTTPClient(client *http.Client) *UpdateCustomWelcomeEmailTestParams {
	var ()
	return &UpdateCustomWelcomeEmailTestParams{
		HTTPClient: client,
	}
}

/*UpdateCustomWelcomeEmailTestParams contains all the parameters to send to the API endpoint
for the update custom welcome email test operation typically these are written to a http.Request
*/
type UpdateCustomWelcomeEmailTestParams struct {

	/*Body
	  Body of the email to be sent.

	*/
	Body *models.WelcomeEmailTest

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the update custom welcome email test params
func (o *UpdateCustomWelcomeEmailTestParams) WithTimeout(timeout time.Duration) *UpdateCustomWelcomeEmailTestParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the update custom welcome email test params
func (o *UpdateCustomWelcomeEmailTestParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the update custom welcome email test params
func (o *UpdateCustomWelcomeEmailTestParams) WithContext(ctx context.Context) *UpdateCustomWelcomeEmailTestParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the update custom welcome email test params
func (o *UpdateCustomWelcomeEmailTestParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the update custom welcome email test params
func (o *UpdateCustomWelcomeEmailTestParams) WithHTTPClient(client *http.Client) *UpdateCustomWelcomeEmailTestParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the update custom welcome email test params
func (o *UpdateCustomWelcomeEmailTestParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the update custom welcome email test params
func (o *UpdateCustomWelcomeEmailTestParams) WithBody(body *models.WelcomeEmailTest) *UpdateCustomWelcomeEmailTestParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the update custom welcome email test params
func (o *UpdateCustomWelcomeEmailTestParams) SetBody(body *models.WelcomeEmailTest) {
	o.Body = body
}

// WriteToRequest writes these params to a swagger request
func (o *UpdateCustomWelcomeEmailTestParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
