// Code generated by go-swagger; DO NOT EDIT.

package user

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewMeParams creates a new MeParams object
// with the default values initialized.
func NewMeParams() *MeParams {
	var ()
	return &MeParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewMeParamsWithTimeout creates a new MeParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewMeParamsWithTimeout(timeout time.Duration) *MeParams {
	var ()
	return &MeParams{

		timeout: timeout,
	}
}

// NewMeParamsWithContext creates a new MeParams object
// with the default values initialized, and the ability to set a context for a request
func NewMeParamsWithContext(ctx context.Context) *MeParams {
	var ()
	return &MeParams{

		Context: ctx,
	}
}

// NewMeParamsWithHTTPClient creates a new MeParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewMeParamsWithHTTPClient(client *http.Client) *MeParams {
	var ()
	return &MeParams{
		HTTPClient: client,
	}
}

/*MeParams contains all the parameters to send to the API endpoint
for the me operation typically these are written to a http.Request
*/
type MeParams struct {

	/*Fields
	  Requested fields.

	*/
	Fields *string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the me params
func (o *MeParams) WithTimeout(timeout time.Duration) *MeParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the me params
func (o *MeParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the me params
func (o *MeParams) WithContext(ctx context.Context) *MeParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the me params
func (o *MeParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the me params
func (o *MeParams) WithHTTPClient(client *http.Client) *MeParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the me params
func (o *MeParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithFields adds the fields to the me params
func (o *MeParams) WithFields(fields *string) *MeParams {
	o.SetFields(fields)
	return o
}

// SetFields adds the fields to the me params
func (o *MeParams) SetFields(fields *string) {
	o.Fields = fields
}

// WriteToRequest writes these params to a swagger request
func (o *MeParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Fields != nil {

		// query param fields
		var qrFields string
		if o.Fields != nil {
			qrFields = *o.Fields
		}
		qFields := qrFields
		if qFields != "" {
			if err := r.SetQueryParam("fields", qFields); err != nil {
				return err
			}
		}

	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
