// Code generated by go-swagger; DO NOT EDIT.

package user

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/swag"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/chenrui333/go-looker/models"
)

// NewUpdateUserCredentialsEmailParams creates a new UpdateUserCredentialsEmailParams object
// with the default values initialized.
func NewUpdateUserCredentialsEmailParams() *UpdateUserCredentialsEmailParams {
	var ()
	return &UpdateUserCredentialsEmailParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewUpdateUserCredentialsEmailParamsWithTimeout creates a new UpdateUserCredentialsEmailParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewUpdateUserCredentialsEmailParamsWithTimeout(timeout time.Duration) *UpdateUserCredentialsEmailParams {
	var ()
	return &UpdateUserCredentialsEmailParams{

		timeout: timeout,
	}
}

// NewUpdateUserCredentialsEmailParamsWithContext creates a new UpdateUserCredentialsEmailParams object
// with the default values initialized, and the ability to set a context for a request
func NewUpdateUserCredentialsEmailParamsWithContext(ctx context.Context) *UpdateUserCredentialsEmailParams {
	var ()
	return &UpdateUserCredentialsEmailParams{

		Context: ctx,
	}
}

// NewUpdateUserCredentialsEmailParamsWithHTTPClient creates a new UpdateUserCredentialsEmailParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewUpdateUserCredentialsEmailParamsWithHTTPClient(client *http.Client) *UpdateUserCredentialsEmailParams {
	var ()
	return &UpdateUserCredentialsEmailParams{
		HTTPClient: client,
	}
}

/*UpdateUserCredentialsEmailParams contains all the parameters to send to the API endpoint
for the update user credentials email operation typically these are written to a http.Request
*/
type UpdateUserCredentialsEmailParams struct {

	/*Body
	  Email/Password Credential

	*/
	Body *models.CredentialsEmail
	/*Fields
	  Requested fields.

	*/
	Fields *string
	/*UserID
	  id of user

	*/
	UserID int64

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the update user credentials email params
func (o *UpdateUserCredentialsEmailParams) WithTimeout(timeout time.Duration) *UpdateUserCredentialsEmailParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the update user credentials email params
func (o *UpdateUserCredentialsEmailParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the update user credentials email params
func (o *UpdateUserCredentialsEmailParams) WithContext(ctx context.Context) *UpdateUserCredentialsEmailParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the update user credentials email params
func (o *UpdateUserCredentialsEmailParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the update user credentials email params
func (o *UpdateUserCredentialsEmailParams) WithHTTPClient(client *http.Client) *UpdateUserCredentialsEmailParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the update user credentials email params
func (o *UpdateUserCredentialsEmailParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the update user credentials email params
func (o *UpdateUserCredentialsEmailParams) WithBody(body *models.CredentialsEmail) *UpdateUserCredentialsEmailParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the update user credentials email params
func (o *UpdateUserCredentialsEmailParams) SetBody(body *models.CredentialsEmail) {
	o.Body = body
}

// WithFields adds the fields to the update user credentials email params
func (o *UpdateUserCredentialsEmailParams) WithFields(fields *string) *UpdateUserCredentialsEmailParams {
	o.SetFields(fields)
	return o
}

// SetFields adds the fields to the update user credentials email params
func (o *UpdateUserCredentialsEmailParams) SetFields(fields *string) {
	o.Fields = fields
}

// WithUserID adds the userID to the update user credentials email params
func (o *UpdateUserCredentialsEmailParams) WithUserID(userID int64) *UpdateUserCredentialsEmailParams {
	o.SetUserID(userID)
	return o
}

// SetUserID adds the userId to the update user credentials email params
func (o *UpdateUserCredentialsEmailParams) SetUserID(userID int64) {
	o.UserID = userID
}

// WriteToRequest writes these params to a swagger request
func (o *UpdateUserCredentialsEmailParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	if o.Fields != nil {

		// query param fields
		var qrFields string
		if o.Fields != nil {
			qrFields = *o.Fields
		}
		qFields := qrFields
		if qFields != "" {
			if err := r.SetQueryParam("fields", qFields); err != nil {
				return err
			}
		}

	}

	// path param user_id
	if err := r.SetPathParam("user_id", swag.FormatInt64(o.UserID)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
