// Code generated by go-swagger; DO NOT EDIT.

package theme

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewActiveThemesParams creates a new ActiveThemesParams object
// with the default values initialized.
func NewActiveThemesParams() *ActiveThemesParams {
	var ()
	return &ActiveThemesParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewActiveThemesParamsWithTimeout creates a new ActiveThemesParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewActiveThemesParamsWithTimeout(timeout time.Duration) *ActiveThemesParams {
	var ()
	return &ActiveThemesParams{

		timeout: timeout,
	}
}

// NewActiveThemesParamsWithContext creates a new ActiveThemesParams object
// with the default values initialized, and the ability to set a context for a request
func NewActiveThemesParamsWithContext(ctx context.Context) *ActiveThemesParams {
	var ()
	return &ActiveThemesParams{

		Context: ctx,
	}
}

// NewActiveThemesParamsWithHTTPClient creates a new ActiveThemesParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewActiveThemesParamsWithHTTPClient(client *http.Client) *ActiveThemesParams {
	var ()
	return &ActiveThemesParams{
		HTTPClient: client,
	}
}

/*ActiveThemesParams contains all the parameters to send to the API endpoint
for the active themes operation typically these are written to a http.Request
*/
type ActiveThemesParams struct {

	/*Fields
	  Requested fields.

	*/
	Fields *string
	/*Name
	  Name of theme

	*/
	Name *string
	/*Ts
	  Timestamp representing the target datetime for the active period. Defaults to 'now'

	*/
	Ts *strfmt.DateTime

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the active themes params
func (o *ActiveThemesParams) WithTimeout(timeout time.Duration) *ActiveThemesParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the active themes params
func (o *ActiveThemesParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the active themes params
func (o *ActiveThemesParams) WithContext(ctx context.Context) *ActiveThemesParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the active themes params
func (o *ActiveThemesParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the active themes params
func (o *ActiveThemesParams) WithHTTPClient(client *http.Client) *ActiveThemesParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the active themes params
func (o *ActiveThemesParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithFields adds the fields to the active themes params
func (o *ActiveThemesParams) WithFields(fields *string) *ActiveThemesParams {
	o.SetFields(fields)
	return o
}

// SetFields adds the fields to the active themes params
func (o *ActiveThemesParams) SetFields(fields *string) {
	o.Fields = fields
}

// WithName adds the name to the active themes params
func (o *ActiveThemesParams) WithName(name *string) *ActiveThemesParams {
	o.SetName(name)
	return o
}

// SetName adds the name to the active themes params
func (o *ActiveThemesParams) SetName(name *string) {
	o.Name = name
}

// WithTs adds the ts to the active themes params
func (o *ActiveThemesParams) WithTs(ts *strfmt.DateTime) *ActiveThemesParams {
	o.SetTs(ts)
	return o
}

// SetTs adds the ts to the active themes params
func (o *ActiveThemesParams) SetTs(ts *strfmt.DateTime) {
	o.Ts = ts
}

// WriteToRequest writes these params to a swagger request
func (o *ActiveThemesParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Fields != nil {

		// query param fields
		var qrFields string
		if o.Fields != nil {
			qrFields = *o.Fields
		}
		qFields := qrFields
		if qFields != "" {
			if err := r.SetQueryParam("fields", qFields); err != nil {
				return err
			}
		}

	}

	if o.Name != nil {

		// query param name
		var qrName string
		if o.Name != nil {
			qrName = *o.Name
		}
		qName := qrName
		if qName != "" {
			if err := r.SetQueryParam("name", qName); err != nil {
				return err
			}
		}

	}

	if o.Ts != nil {

		// query param ts
		var qrTs strfmt.DateTime
		if o.Ts != nil {
			qrTs = *o.Ts
		}
		qTs := qrTs.String()
		if qTs != "" {
			if err := r.SetQueryParam("ts", qTs); err != nil {
				return err
			}
		}

	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
