// Code generated by go-swagger; DO NOT EDIT.

package theme

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewAllThemesParams creates a new AllThemesParams object
// with the default values initialized.
func NewAllThemesParams() *AllThemesParams {
	var ()
	return &AllThemesParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewAllThemesParamsWithTimeout creates a new AllThemesParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewAllThemesParamsWithTimeout(timeout time.Duration) *AllThemesParams {
	var ()
	return &AllThemesParams{

		timeout: timeout,
	}
}

// NewAllThemesParamsWithContext creates a new AllThemesParams object
// with the default values initialized, and the ability to set a context for a request
func NewAllThemesParamsWithContext(ctx context.Context) *AllThemesParams {
	var ()
	return &AllThemesParams{

		Context: ctx,
	}
}

// NewAllThemesParamsWithHTTPClient creates a new AllThemesParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewAllThemesParamsWithHTTPClient(client *http.Client) *AllThemesParams {
	var ()
	return &AllThemesParams{
		HTTPClient: client,
	}
}

/*AllThemesParams contains all the parameters to send to the API endpoint
for the all themes operation typically these are written to a http.Request
*/
type AllThemesParams struct {

	/*Fields
	  Requested fields.

	*/
	Fields *string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the all themes params
func (o *AllThemesParams) WithTimeout(timeout time.Duration) *AllThemesParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the all themes params
func (o *AllThemesParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the all themes params
func (o *AllThemesParams) WithContext(ctx context.Context) *AllThemesParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the all themes params
func (o *AllThemesParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the all themes params
func (o *AllThemesParams) WithHTTPClient(client *http.Client) *AllThemesParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the all themes params
func (o *AllThemesParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithFields adds the fields to the all themes params
func (o *AllThemesParams) WithFields(fields *string) *AllThemesParams {
	o.SetFields(fields)
	return o
}

// SetFields adds the fields to the all themes params
func (o *AllThemesParams) SetFields(fields *string) {
	o.Fields = fields
}

// WriteToRequest writes these params to a swagger request
func (o *AllThemesParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Fields != nil {

		// query param fields
		var qrFields string
		if o.Fields != nil {
			qrFields = *o.Fields
		}
		qFields := qrFields
		if qFields != "" {
			if err := r.SetQueryParam("fields", qFields); err != nil {
				return err
			}
		}

	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
