// Code generated by go-swagger; DO NOT EDIT.

package theme

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewDefaultThemeParams creates a new DefaultThemeParams object
// with the default values initialized.
func NewDefaultThemeParams() *DefaultThemeParams {
	var ()
	return &DefaultThemeParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewDefaultThemeParamsWithTimeout creates a new DefaultThemeParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewDefaultThemeParamsWithTimeout(timeout time.Duration) *DefaultThemeParams {
	var ()
	return &DefaultThemeParams{

		timeout: timeout,
	}
}

// NewDefaultThemeParamsWithContext creates a new DefaultThemeParams object
// with the default values initialized, and the ability to set a context for a request
func NewDefaultThemeParamsWithContext(ctx context.Context) *DefaultThemeParams {
	var ()
	return &DefaultThemeParams{

		Context: ctx,
	}
}

// NewDefaultThemeParamsWithHTTPClient creates a new DefaultThemeParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewDefaultThemeParamsWithHTTPClient(client *http.Client) *DefaultThemeParams {
	var ()
	return &DefaultThemeParams{
		HTTPClient: client,
	}
}

/*DefaultThemeParams contains all the parameters to send to the API endpoint
for the default theme operation typically these are written to a http.Request
*/
type DefaultThemeParams struct {

	/*Ts
	  Timestamp representing the target datetime for the active period. Defaults to 'now'

	*/
	Ts *strfmt.DateTime

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the default theme params
func (o *DefaultThemeParams) WithTimeout(timeout time.Duration) *DefaultThemeParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the default theme params
func (o *DefaultThemeParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the default theme params
func (o *DefaultThemeParams) WithContext(ctx context.Context) *DefaultThemeParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the default theme params
func (o *DefaultThemeParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the default theme params
func (o *DefaultThemeParams) WithHTTPClient(client *http.Client) *DefaultThemeParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the default theme params
func (o *DefaultThemeParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithTs adds the ts to the default theme params
func (o *DefaultThemeParams) WithTs(ts *strfmt.DateTime) *DefaultThemeParams {
	o.SetTs(ts)
	return o
}

// SetTs adds the ts to the default theme params
func (o *DefaultThemeParams) SetTs(ts *strfmt.DateTime) {
	o.Ts = ts
}

// WriteToRequest writes these params to a swagger request
func (o *DefaultThemeParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Ts != nil {

		// query param ts
		var qrTs strfmt.DateTime
		if o.Ts != nil {
			qrTs = *o.Ts
		}
		qTs := qrTs.String()
		if qTs != "" {
			if err := r.SetQueryParam("ts", qTs); err != nil {
				return err
			}
		}

	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
