// Code generated by go-swagger; DO NOT EDIT.

package space

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/chenrui333/go-looker/models"
)

// NewUpdateSpaceParams creates a new UpdateSpaceParams object
// with the default values initialized.
func NewUpdateSpaceParams() *UpdateSpaceParams {
	var ()
	return &UpdateSpaceParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewUpdateSpaceParamsWithTimeout creates a new UpdateSpaceParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewUpdateSpaceParamsWithTimeout(timeout time.Duration) *UpdateSpaceParams {
	var ()
	return &UpdateSpaceParams{

		timeout: timeout,
	}
}

// NewUpdateSpaceParamsWithContext creates a new UpdateSpaceParams object
// with the default values initialized, and the ability to set a context for a request
func NewUpdateSpaceParamsWithContext(ctx context.Context) *UpdateSpaceParams {
	var ()
	return &UpdateSpaceParams{

		Context: ctx,
	}
}

// NewUpdateSpaceParamsWithHTTPClient creates a new UpdateSpaceParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewUpdateSpaceParamsWithHTTPClient(client *http.Client) *UpdateSpaceParams {
	var ()
	return &UpdateSpaceParams{
		HTTPClient: client,
	}
}

/*UpdateSpaceParams contains all the parameters to send to the API endpoint
for the update space operation typically these are written to a http.Request
*/
type UpdateSpaceParams struct {

	/*Body
	  Space

	*/
	Body *models.Space
	/*SpaceID
	  Id of space

	*/
	SpaceID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the update space params
func (o *UpdateSpaceParams) WithTimeout(timeout time.Duration) *UpdateSpaceParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the update space params
func (o *UpdateSpaceParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the update space params
func (o *UpdateSpaceParams) WithContext(ctx context.Context) *UpdateSpaceParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the update space params
func (o *UpdateSpaceParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the update space params
func (o *UpdateSpaceParams) WithHTTPClient(client *http.Client) *UpdateSpaceParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the update space params
func (o *UpdateSpaceParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the update space params
func (o *UpdateSpaceParams) WithBody(body *models.Space) *UpdateSpaceParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the update space params
func (o *UpdateSpaceParams) SetBody(body *models.Space) {
	o.Body = body
}

// WithSpaceID adds the spaceID to the update space params
func (o *UpdateSpaceParams) WithSpaceID(spaceID string) *UpdateSpaceParams {
	o.SetSpaceID(spaceID)
	return o
}

// SetSpaceID adds the spaceId to the update space params
func (o *UpdateSpaceParams) SetSpaceID(spaceID string) {
	o.SpaceID = spaceID
}

// WriteToRequest writes these params to a swagger request
func (o *UpdateSpaceParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	// path param space_id
	if err := r.SetPathParam("space_id", o.SpaceID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
