// Code generated by go-swagger; DO NOT EDIT.

package datagroup

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// New creates a new datagroup API client.
func New(transport runtime.ClientTransport, formats strfmt.Registry) *Client {
	return &Client{transport: transport, formats: formats}
}

/*
Client for datagroup API
*/
type Client struct {
	transport runtime.ClientTransport
	formats   strfmt.Registry
}

/*
AllDatagroups gets all datagroups

### Get information about all datagroups.

*/
func (a *Client) AllDatagroups(params *AllDatagroupsParams) (*AllDatagroupsOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewAllDatagroupsParams()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "all_datagroups",
		Method:             "GET",
		PathPattern:        "/datagroups",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &AllDatagroupsReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	return result.(*AllDatagroupsOK), nil

}

/*
Datagroup gets datagroup

### Get information about a datagroup.

*/
func (a *Client) Datagroup(params *DatagroupParams) (*DatagroupOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewDatagroupParams()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "datagroup",
		Method:             "GET",
		PathPattern:        "/datagroups/{datagroup_id}",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &DatagroupReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	return result.(*DatagroupOK), nil

}

/*
UpdateDatagroup updates datagroup

### Update a datagroup using the specified params.

*/
func (a *Client) UpdateDatagroup(params *UpdateDatagroupParams) (*UpdateDatagroupOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewUpdateDatagroupParams()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "update_datagroup",
		Method:             "PATCH",
		PathPattern:        "/datagroups/{datagroup_id}",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &UpdateDatagroupReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	return result.(*UpdateDatagroupOK), nil

}

// SetTransport changes the transport on the client
func (a *Client) SetTransport(transport runtime.ClientTransport) {
	a.transport = transport
}
