// Code generated by go-swagger; DO NOT EDIT.

package user_attribute

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/chenrui333/go-looker/models"
)

// CreateUserAttributeReader is a Reader for the CreateUserAttribute structure.
type CreateUserAttributeReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *CreateUserAttributeReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewCreateUserAttributeOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 400:
		result := NewCreateUserAttributeBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 404:
		result := NewCreateUserAttributeNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 409:
		result := NewCreateUserAttributeConflict()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 422:
		result := NewCreateUserAttributeUnprocessableEntity()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewCreateUserAttributeOK creates a CreateUserAttributeOK with default headers values
func NewCreateUserAttributeOK() *CreateUserAttributeOK {
	return &CreateUserAttributeOK{}
}

/*CreateUserAttributeOK handles this case with default header values.

User Attribute
*/
type CreateUserAttributeOK struct {
	Payload *models.UserAttribute
}

func (o *CreateUserAttributeOK) Error() string {
	return fmt.Sprintf("[POST /user_attributes][%d] createUserAttributeOK  %+v", 200, o.Payload)
}

func (o *CreateUserAttributeOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.UserAttribute)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewCreateUserAttributeBadRequest creates a CreateUserAttributeBadRequest with default headers values
func NewCreateUserAttributeBadRequest() *CreateUserAttributeBadRequest {
	return &CreateUserAttributeBadRequest{}
}

/*CreateUserAttributeBadRequest handles this case with default header values.

Bad Request
*/
type CreateUserAttributeBadRequest struct {
	Payload *models.Error
}

func (o *CreateUserAttributeBadRequest) Error() string {
	return fmt.Sprintf("[POST /user_attributes][%d] createUserAttributeBadRequest  %+v", 400, o.Payload)
}

func (o *CreateUserAttributeBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewCreateUserAttributeNotFound creates a CreateUserAttributeNotFound with default headers values
func NewCreateUserAttributeNotFound() *CreateUserAttributeNotFound {
	return &CreateUserAttributeNotFound{}
}

/*CreateUserAttributeNotFound handles this case with default header values.

Not Found
*/
type CreateUserAttributeNotFound struct {
	Payload *models.Error
}

func (o *CreateUserAttributeNotFound) Error() string {
	return fmt.Sprintf("[POST /user_attributes][%d] createUserAttributeNotFound  %+v", 404, o.Payload)
}

func (o *CreateUserAttributeNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewCreateUserAttributeConflict creates a CreateUserAttributeConflict with default headers values
func NewCreateUserAttributeConflict() *CreateUserAttributeConflict {
	return &CreateUserAttributeConflict{}
}

/*CreateUserAttributeConflict handles this case with default header values.

Resource Already Exists
*/
type CreateUserAttributeConflict struct {
	Payload *models.Error
}

func (o *CreateUserAttributeConflict) Error() string {
	return fmt.Sprintf("[POST /user_attributes][%d] createUserAttributeConflict  %+v", 409, o.Payload)
}

func (o *CreateUserAttributeConflict) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewCreateUserAttributeUnprocessableEntity creates a CreateUserAttributeUnprocessableEntity with default headers values
func NewCreateUserAttributeUnprocessableEntity() *CreateUserAttributeUnprocessableEntity {
	return &CreateUserAttributeUnprocessableEntity{}
}

/*CreateUserAttributeUnprocessableEntity handles this case with default header values.

Validation Error
*/
type CreateUserAttributeUnprocessableEntity struct {
	Payload *models.ValidationError
}

func (o *CreateUserAttributeUnprocessableEntity) Error() string {
	return fmt.Sprintf("[POST /user_attributes][%d] createUserAttributeUnprocessableEntity  %+v", 422, o.Payload)
}

func (o *CreateUserAttributeUnprocessableEntity) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ValidationError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
