// Code generated by go-swagger; DO NOT EDIT.

package user_attribute

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/chenrui333/go-looker/models"
)

// SetUserAttributeGroupValuesReader is a Reader for the SetUserAttributeGroupValues structure.
type SetUserAttributeGroupValuesReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *SetUserAttributeGroupValuesReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewSetUserAttributeGroupValuesOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewSetUserAttributeGroupValuesBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewSetUserAttributeGroupValuesNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 409:
		result := NewSetUserAttributeGroupValuesConflict()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 422:
		result := NewSetUserAttributeGroupValuesUnprocessableEntity()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewSetUserAttributeGroupValuesOK creates a SetUserAttributeGroupValuesOK with default headers values
func NewSetUserAttributeGroupValuesOK() *SetUserAttributeGroupValuesOK {
	return &SetUserAttributeGroupValuesOK{}
}

/*SetUserAttributeGroupValuesOK handles this case with default header values.

Array of group values.
*/
type SetUserAttributeGroupValuesOK struct {
	Payload []*models.UserAttributeGroupValue
}

func (o *SetUserAttributeGroupValuesOK) Error() string {
	return fmt.Sprintf("[POST /user_attributes/{user_attribute_id}/group_values][%d] setUserAttributeGroupValuesOK  %+v", 200, o.Payload)
}

func (o *SetUserAttributeGroupValuesOK) GetPayload() []*models.UserAttributeGroupValue {
	return o.Payload
}

func (o *SetUserAttributeGroupValuesOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewSetUserAttributeGroupValuesBadRequest creates a SetUserAttributeGroupValuesBadRequest with default headers values
func NewSetUserAttributeGroupValuesBadRequest() *SetUserAttributeGroupValuesBadRequest {
	return &SetUserAttributeGroupValuesBadRequest{}
}

/*SetUserAttributeGroupValuesBadRequest handles this case with default header values.

Bad Request
*/
type SetUserAttributeGroupValuesBadRequest struct {
	Payload *models.Error
}

func (o *SetUserAttributeGroupValuesBadRequest) Error() string {
	return fmt.Sprintf("[POST /user_attributes/{user_attribute_id}/group_values][%d] setUserAttributeGroupValuesBadRequest  %+v", 400, o.Payload)
}

func (o *SetUserAttributeGroupValuesBadRequest) GetPayload() *models.Error {
	return o.Payload
}

func (o *SetUserAttributeGroupValuesBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewSetUserAttributeGroupValuesNotFound creates a SetUserAttributeGroupValuesNotFound with default headers values
func NewSetUserAttributeGroupValuesNotFound() *SetUserAttributeGroupValuesNotFound {
	return &SetUserAttributeGroupValuesNotFound{}
}

/*SetUserAttributeGroupValuesNotFound handles this case with default header values.

Not Found
*/
type SetUserAttributeGroupValuesNotFound struct {
	Payload *models.Error
}

func (o *SetUserAttributeGroupValuesNotFound) Error() string {
	return fmt.Sprintf("[POST /user_attributes/{user_attribute_id}/group_values][%d] setUserAttributeGroupValuesNotFound  %+v", 404, o.Payload)
}

func (o *SetUserAttributeGroupValuesNotFound) GetPayload() *models.Error {
	return o.Payload
}

func (o *SetUserAttributeGroupValuesNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewSetUserAttributeGroupValuesConflict creates a SetUserAttributeGroupValuesConflict with default headers values
func NewSetUserAttributeGroupValuesConflict() *SetUserAttributeGroupValuesConflict {
	return &SetUserAttributeGroupValuesConflict{}
}

/*SetUserAttributeGroupValuesConflict handles this case with default header values.

Resource Already Exists
*/
type SetUserAttributeGroupValuesConflict struct {
	Payload *models.Error
}

func (o *SetUserAttributeGroupValuesConflict) Error() string {
	return fmt.Sprintf("[POST /user_attributes/{user_attribute_id}/group_values][%d] setUserAttributeGroupValuesConflict  %+v", 409, o.Payload)
}

func (o *SetUserAttributeGroupValuesConflict) GetPayload() *models.Error {
	return o.Payload
}

func (o *SetUserAttributeGroupValuesConflict) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewSetUserAttributeGroupValuesUnprocessableEntity creates a SetUserAttributeGroupValuesUnprocessableEntity with default headers values
func NewSetUserAttributeGroupValuesUnprocessableEntity() *SetUserAttributeGroupValuesUnprocessableEntity {
	return &SetUserAttributeGroupValuesUnprocessableEntity{}
}

/*SetUserAttributeGroupValuesUnprocessableEntity handles this case with default header values.

Validation Error
*/
type SetUserAttributeGroupValuesUnprocessableEntity struct {
	Payload *models.ValidationError
}

func (o *SetUserAttributeGroupValuesUnprocessableEntity) Error() string {
	return fmt.Sprintf("[POST /user_attributes/{user_attribute_id}/group_values][%d] setUserAttributeGroupValuesUnprocessableEntity  %+v", 422, o.Payload)
}

func (o *SetUserAttributeGroupValuesUnprocessableEntity) GetPayload() *models.ValidationError {
	return o.Payload
}

func (o *SetUserAttributeGroupValuesUnprocessableEntity) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ValidationError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
