// Code generated by go-swagger; DO NOT EDIT.

package user_attribute

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/chenrui333/go-looker/models"
)

// UpdateUserAttributeReader is a Reader for the UpdateUserAttribute structure.
type UpdateUserAttributeReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *UpdateUserAttributeReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewUpdateUserAttributeOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 400:
		result := NewUpdateUserAttributeBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 404:
		result := NewUpdateUserAttributeNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 422:
		result := NewUpdateUserAttributeUnprocessableEntity()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewUpdateUserAttributeOK creates a UpdateUserAttributeOK with default headers values
func NewUpdateUserAttributeOK() *UpdateUserAttributeOK {
	return &UpdateUserAttributeOK{}
}

/*UpdateUserAttributeOK handles this case with default header values.

User Attribute
*/
type UpdateUserAttributeOK struct {
	Payload *models.UserAttribute
}

func (o *UpdateUserAttributeOK) Error() string {
	return fmt.Sprintf("[PATCH /user_attributes/{user_attribute_id}][%d] updateUserAttributeOK  %+v", 200, o.Payload)
}

func (o *UpdateUserAttributeOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.UserAttribute)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewUpdateUserAttributeBadRequest creates a UpdateUserAttributeBadRequest with default headers values
func NewUpdateUserAttributeBadRequest() *UpdateUserAttributeBadRequest {
	return &UpdateUserAttributeBadRequest{}
}

/*UpdateUserAttributeBadRequest handles this case with default header values.

Bad Request
*/
type UpdateUserAttributeBadRequest struct {
	Payload *models.Error
}

func (o *UpdateUserAttributeBadRequest) Error() string {
	return fmt.Sprintf("[PATCH /user_attributes/{user_attribute_id}][%d] updateUserAttributeBadRequest  %+v", 400, o.Payload)
}

func (o *UpdateUserAttributeBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewUpdateUserAttributeNotFound creates a UpdateUserAttributeNotFound with default headers values
func NewUpdateUserAttributeNotFound() *UpdateUserAttributeNotFound {
	return &UpdateUserAttributeNotFound{}
}

/*UpdateUserAttributeNotFound handles this case with default header values.

Not Found
*/
type UpdateUserAttributeNotFound struct {
	Payload *models.Error
}

func (o *UpdateUserAttributeNotFound) Error() string {
	return fmt.Sprintf("[PATCH /user_attributes/{user_attribute_id}][%d] updateUserAttributeNotFound  %+v", 404, o.Payload)
}

func (o *UpdateUserAttributeNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewUpdateUserAttributeUnprocessableEntity creates a UpdateUserAttributeUnprocessableEntity with default headers values
func NewUpdateUserAttributeUnprocessableEntity() *UpdateUserAttributeUnprocessableEntity {
	return &UpdateUserAttributeUnprocessableEntity{}
}

/*UpdateUserAttributeUnprocessableEntity handles this case with default header values.

Validation Error
*/
type UpdateUserAttributeUnprocessableEntity struct {
	Payload *models.ValidationError
}

func (o *UpdateUserAttributeUnprocessableEntity) Error() string {
	return fmt.Sprintf("[PATCH /user_attributes/{user_attribute_id}][%d] updateUserAttributeUnprocessableEntity  %+v", 422, o.Payload)
}

func (o *UpdateUserAttributeUnprocessableEntity) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ValidationError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
