// Code generated by go-swagger; DO NOT EDIT.

package homepage

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/swag"

	strfmt "github.com/go-openapi/strfmt"
)

// NewDeleteHomepageItemParams creates a new DeleteHomepageItemParams object
// with the default values initialized.
func NewDeleteHomepageItemParams() *DeleteHomepageItemParams {
	var ()
	return &DeleteHomepageItemParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewDeleteHomepageItemParamsWithTimeout creates a new DeleteHomepageItemParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewDeleteHomepageItemParamsWithTimeout(timeout time.Duration) *DeleteHomepageItemParams {
	var ()
	return &DeleteHomepageItemParams{

		timeout: timeout,
	}
}

// NewDeleteHomepageItemParamsWithContext creates a new DeleteHomepageItemParams object
// with the default values initialized, and the ability to set a context for a request
func NewDeleteHomepageItemParamsWithContext(ctx context.Context) *DeleteHomepageItemParams {
	var ()
	return &DeleteHomepageItemParams{

		Context: ctx,
	}
}

// NewDeleteHomepageItemParamsWithHTTPClient creates a new DeleteHomepageItemParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewDeleteHomepageItemParamsWithHTTPClient(client *http.Client) *DeleteHomepageItemParams {
	var ()
	return &DeleteHomepageItemParams{
		HTTPClient: client,
	}
}

/*DeleteHomepageItemParams contains all the parameters to send to the API endpoint
for the delete homepage item operation typically these are written to a http.Request
*/
type DeleteHomepageItemParams struct {

	/*HomepageItemID
	  Id of homepage_item

	*/
	HomepageItemID int64

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the delete homepage item params
func (o *DeleteHomepageItemParams) WithTimeout(timeout time.Duration) *DeleteHomepageItemParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the delete homepage item params
func (o *DeleteHomepageItemParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the delete homepage item params
func (o *DeleteHomepageItemParams) WithContext(ctx context.Context) *DeleteHomepageItemParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the delete homepage item params
func (o *DeleteHomepageItemParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the delete homepage item params
func (o *DeleteHomepageItemParams) WithHTTPClient(client *http.Client) *DeleteHomepageItemParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the delete homepage item params
func (o *DeleteHomepageItemParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithHomepageItemID adds the homepageItemID to the delete homepage item params
func (o *DeleteHomepageItemParams) WithHomepageItemID(homepageItemID int64) *DeleteHomepageItemParams {
	o.SetHomepageItemID(homepageItemID)
	return o
}

// SetHomepageItemID adds the homepageItemId to the delete homepage item params
func (o *DeleteHomepageItemParams) SetHomepageItemID(homepageItemID int64) {
	o.HomepageItemID = homepageItemID
}

// WriteToRequest writes these params to a swagger request
func (o *DeleteHomepageItemParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param homepage_item_id
	if err := r.SetPathParam("homepage_item_id", swag.FormatInt64(o.HomepageItemID)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
