// Code generated by go-swagger; DO NOT EDIT.

package auth

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewDeleteSamlTestConfigParams creates a new DeleteSamlTestConfigParams object
// with the default values initialized.
func NewDeleteSamlTestConfigParams() *DeleteSamlTestConfigParams {
	var ()
	return &DeleteSamlTestConfigParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewDeleteSamlTestConfigParamsWithTimeout creates a new DeleteSamlTestConfigParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewDeleteSamlTestConfigParamsWithTimeout(timeout time.Duration) *DeleteSamlTestConfigParams {
	var ()
	return &DeleteSamlTestConfigParams{

		timeout: timeout,
	}
}

// NewDeleteSamlTestConfigParamsWithContext creates a new DeleteSamlTestConfigParams object
// with the default values initialized, and the ability to set a context for a request
func NewDeleteSamlTestConfigParamsWithContext(ctx context.Context) *DeleteSamlTestConfigParams {
	var ()
	return &DeleteSamlTestConfigParams{

		Context: ctx,
	}
}

// NewDeleteSamlTestConfigParamsWithHTTPClient creates a new DeleteSamlTestConfigParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewDeleteSamlTestConfigParamsWithHTTPClient(client *http.Client) *DeleteSamlTestConfigParams {
	var ()
	return &DeleteSamlTestConfigParams{
		HTTPClient: client,
	}
}

/*DeleteSamlTestConfigParams contains all the parameters to send to the API endpoint
for the delete saml test config operation typically these are written to a http.Request
*/
type DeleteSamlTestConfigParams struct {

	/*TestSlug
	  Slug of test config

	*/
	TestSlug string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the delete saml test config params
func (o *DeleteSamlTestConfigParams) WithTimeout(timeout time.Duration) *DeleteSamlTestConfigParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the delete saml test config params
func (o *DeleteSamlTestConfigParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the delete saml test config params
func (o *DeleteSamlTestConfigParams) WithContext(ctx context.Context) *DeleteSamlTestConfigParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the delete saml test config params
func (o *DeleteSamlTestConfigParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the delete saml test config params
func (o *DeleteSamlTestConfigParams) WithHTTPClient(client *http.Client) *DeleteSamlTestConfigParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the delete saml test config params
func (o *DeleteSamlTestConfigParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithTestSlug adds the testSlug to the delete saml test config params
func (o *DeleteSamlTestConfigParams) WithTestSlug(testSlug string) *DeleteSamlTestConfigParams {
	o.SetTestSlug(testSlug)
	return o
}

// SetTestSlug adds the testSlug to the delete saml test config params
func (o *DeleteSamlTestConfigParams) SetTestSlug(testSlug string) {
	o.TestSlug = testSlug
}

// WriteToRequest writes these params to a swagger request
func (o *DeleteSamlTestConfigParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param test_slug
	if err := r.SetPathParam("test_slug", o.TestSlug); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
