// Code generated by go-swagger; DO NOT EDIT.

package project

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/chenrui333/go-looker/models"
)

// NewCreateGitBranchParams creates a new CreateGitBranchParams object
// with the default values initialized.
func NewCreateGitBranchParams() *CreateGitBranchParams {
	var ()
	return &CreateGitBranchParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewCreateGitBranchParamsWithTimeout creates a new CreateGitBranchParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewCreateGitBranchParamsWithTimeout(timeout time.Duration) *CreateGitBranchParams {
	var ()
	return &CreateGitBranchParams{

		timeout: timeout,
	}
}

// NewCreateGitBranchParamsWithContext creates a new CreateGitBranchParams object
// with the default values initialized, and the ability to set a context for a request
func NewCreateGitBranchParamsWithContext(ctx context.Context) *CreateGitBranchParams {
	var ()
	return &CreateGitBranchParams{

		Context: ctx,
	}
}

// NewCreateGitBranchParamsWithHTTPClient creates a new CreateGitBranchParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewCreateGitBranchParamsWithHTTPClient(client *http.Client) *CreateGitBranchParams {
	var ()
	return &CreateGitBranchParams{
		HTTPClient: client,
	}
}

/*CreateGitBranchParams contains all the parameters to send to the API endpoint
for the create git branch operation typically these are written to a http.Request
*/
type CreateGitBranchParams struct {

	/*Body
	  Git Branch

	*/
	Body *models.GitBranch
	/*ProjectID
	  Project Id

	*/
	ProjectID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the create git branch params
func (o *CreateGitBranchParams) WithTimeout(timeout time.Duration) *CreateGitBranchParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the create git branch params
func (o *CreateGitBranchParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the create git branch params
func (o *CreateGitBranchParams) WithContext(ctx context.Context) *CreateGitBranchParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the create git branch params
func (o *CreateGitBranchParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the create git branch params
func (o *CreateGitBranchParams) WithHTTPClient(client *http.Client) *CreateGitBranchParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the create git branch params
func (o *CreateGitBranchParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the create git branch params
func (o *CreateGitBranchParams) WithBody(body *models.GitBranch) *CreateGitBranchParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the create git branch params
func (o *CreateGitBranchParams) SetBody(body *models.GitBranch) {
	o.Body = body
}

// WithProjectID adds the projectID to the create git branch params
func (o *CreateGitBranchParams) WithProjectID(projectID string) *CreateGitBranchParams {
	o.SetProjectID(projectID)
	return o
}

// SetProjectID adds the projectId to the create git branch params
func (o *CreateGitBranchParams) SetProjectID(projectID string) {
	o.ProjectID = projectID
}

// WriteToRequest writes these params to a swagger request
func (o *CreateGitBranchParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	// path param project_id
	if err := r.SetPathParam("project_id", o.ProjectID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
