name: CI

on:
  push:
    paths-ignore:
    - 'README.md'
    - '**/README.md'

jobs:
   build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/action-builder/shell@master
        run: make generate
