// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/swag"
)

// ContentValidationDashboardElement content validation dashboard element
// swagger:model ContentValidationDashboardElement
type ContentValidationDashboardElement struct {

	// Text tile body text
	// Read Only: true
	BodyText string `json:"body_text,omitempty"`

	// Id of Dashboard
	// Read Only: true
	DashboardID string `json:"dashboard_id,omitempty"`

	// Unique Id
	// Read Only: true
	ID string `json:"id,omitempty"`

	// Id Of Look
	// Read Only: true
	LookID string `json:"look_id,omitempty"`

	// Note Display
	// Read Only: true
	NoteDisplay string `json:"note_display,omitempty"`

	// Note State
	// Read Only: true
	NoteState string `json:"note_state,omitempty"`

	// Note Text
	// Read Only: true
	NoteText string `json:"note_text,omitempty"`

	// Note Text as Html
	// Read Only: true
	NoteTextAsHTML string `json:"note_text_as_html,omitempty"`

	// Id Of Query
	// Read Only: true
	QueryID int64 `json:"query_id,omitempty"`

	// Text tile subtitle text
	// Read Only: true
	SubtitleText string `json:"subtitle_text,omitempty"`

	// Title of dashboard element
	// Read Only: true
	Title string `json:"title,omitempty"`

	// Whether title is hidden
	// Read Only: true
	TitleHidden *bool `json:"title_hidden,omitempty"`

	// Text tile title
	// Read Only: true
	TitleText string `json:"title_text,omitempty"`

	// Type
	// Read Only: true
	Type string `json:"type,omitempty"`
}

// Validate validates this content validation dashboard element
func (m *ContentValidationDashboardElement) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *ContentValidationDashboardElement) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ContentValidationDashboardElement) UnmarshalBinary(b []byte) error {
	var res ContentValidationDashboardElement
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
