// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"strconv"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// LDAPUserAttributeRead l d a p user attribute read
// swagger:model LDAPUserAttributeRead
type LDAPUserAttributeRead struct {

	// Operations the current user is able to perform on this object
	// Read Only: true
	Can map[string]bool `json:"can,omitempty"`

	// Name of User Attribute in LDAP
	// Read Only: true
	Name string `json:"name,omitempty"`

	// Required to be in LDAP assertion for login to be allowed to succeed
	// Read Only: true
	Required *bool `json:"required,omitempty"`

	// Link to LDAP config
	// Read Only: true
	// Format: uri
	URL strfmt.URI `json:"url,omitempty"`

	// Looker User Attributes
	// Read Only: true
	UserAttributes []*UserAttribute `json:"user_attributes"`
}

// Validate validates this l d a p user attribute read
func (m *LDAPUserAttributeRead) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateURL(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateUserAttributes(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *LDAPUserAttributeRead) validateURL(formats strfmt.Registry) error {

	if swag.IsZero(m.URL) { // not required
		return nil
	}

	if err := validate.FormatOf("url", "body", "uri", m.URL.String(), formats); err != nil {
		return err
	}

	return nil
}

func (m *LDAPUserAttributeRead) validateUserAttributes(formats strfmt.Registry) error {

	if swag.IsZero(m.UserAttributes) { // not required
		return nil
	}

	for i := 0; i < len(m.UserAttributes); i++ {
		if swag.IsZero(m.UserAttributes[i]) { // not required
			continue
		}

		if m.UserAttributes[i] != nil {
			if err := m.UserAttributes[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("user_attributes" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (m *LDAPUserAttributeRead) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *LDAPUserAttributeRead) UnmarshalBinary(b []byte) error {
	var res LDAPUserAttributeRead
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
