// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/swag"
)

// LookmlModelExploreSet lookml model explore set
// swagger:model LookmlModelExploreSet
type LookmlModelExploreSet struct {

	// Name
	// Read Only: true
	Name string `json:"name,omitempty"`

	// Value set
	// Read Only: true
	Value []string `json:"value"`
}

// Validate validates this lookml model explore set
func (m *LookmlModelExploreSet) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *LookmlModelExploreSet) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *LookmlModelExploreSet) UnmarshalBinary(b []byte) error {
	var res LookmlModelExploreSet
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
